/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["changeStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["archive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch: operations["update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateApplicationRequest: {
            companyName: string;
            roleTitle: string;
            /** @enum {string} */
            status?: "DISCOVERED" | "SAVED" | "APPLIED" | "SCREEN" | "INTERVIEW" | "OFFER" | "ACCEPTED" | "REJECTED" | "GHOSTED" | "WITHDRAWN";
            source?: string;
            jobUrl?: string;
            location?: string;
            /** @enum {string} */
            remoteType?: "ONSITE" | "HYBRID" | "REMOTE";
            /** Format: int32 */
            salaryMin?: number;
            /** Format: int32 */
            salaryMax?: number;
            currency?: string;
            /** Format: int32 */
            priority?: number;
            resumeVersion?: string;
            notes?: string;
            /** Format: date-time */
            appliedAt?: string;
        };
        ApplicationResponse: {
            /** Format: int64 */
            id: number;
            company: components["schemas"]["CompanySummary"];
            roleTitle: string;
            /** @enum {string} */
            status: "DISCOVERED" | "SAVED" | "APPLIED" | "SCREEN" | "INTERVIEW" | "OFFER" | "ACCEPTED" | "REJECTED" | "GHOSTED" | "WITHDRAWN";
            allowedNextStatuses: ("DISCOVERED" | "SAVED" | "APPLIED" | "SCREEN" | "INTERVIEW" | "OFFER" | "ACCEPTED" | "REJECTED" | "GHOSTED" | "WITHDRAWN")[];
            source?: string;
            jobUrl?: string;
            location?: string;
            /** @enum {string} */
            remoteType?: "ONSITE" | "HYBRID" | "REMOTE";
            /** Format: int32 */
            salaryMin?: number;
            /** Format: int32 */
            salaryMax?: number;
            currency?: string;
            /** Format: int32 */
            priority: number;
            resumeVersion?: string;
            notes?: string;
            /** Format: date-time */
            appliedAt?: string;
            archived: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CompanySummary: {
            /** Format: int64 */
            id: number;
            name: string;
            website?: string;
        };
        ChangeStatusRequest: {
            /** @enum {string} */
            status: "DISCOVERED" | "SAVED" | "APPLIED" | "SCREEN" | "INTERVIEW" | "OFFER" | "ACCEPTED" | "REJECTED" | "GHOSTED" | "WITHDRAWN";
            note?: string;
        };
        UpdateApplicationRequest: {
            companyName?: string;
            roleTitle?: string;
            source?: string;
            jobUrl?: string;
            location?: string;
            /** @enum {string} */
            remoteType?: "ONSITE" | "HYBRID" | "REMOTE";
            /** Format: int32 */
            salaryMin?: number;
            /** Format: int32 */
            salaryMax?: number;
            currency?: string;
            /** Format: int32 */
            priority?: number;
            resumeVersion?: string;
            notes?: string;
            /** Format: date-time */
            appliedAt?: string;
            archived?: boolean;
        };
        PageResponseApplicationResponse: {
            content: components["schemas"]["ApplicationResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
            first: boolean;
            last: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: {
                status?: "DISCOVERED" | "SAVED" | "APPLIED" | "SCREEN" | "INTERVIEW" | "OFFER" | "ACCEPTED" | "REJECTED" | "GHOSTED" | "WITHDRAWN";
                company?: string;
                includeArchived?: boolean;
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseApplicationResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApplicationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApplicationResponse"];
                };
            };
        };
    };
    changeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApplicationResponse"];
                };
            };
        };
    };
    archive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApplicationResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateApplicationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApplicationResponse"];
                };
            };
        };
    };
}
