export const CURRENCY_OPTIONS = [
  ['USD', 'US Dollar'],
  ['CAD', 'Canadian Dollar'],
  ['EUR', 'Euro'],
  ['GBP', 'British Pound'],
  ['AUD', 'Australian Dollar'],
  ['NZD', 'New Zealand Dollar'],
  ['CHF', 'Swiss Franc'],
  ['JPY', 'Japanese Yen'],
  ['CNY', 'Chinese Yuan'],
  ['HKD', 'Hong Kong Dollar'],
  ['SGD', 'Singapore Dollar'],
  ['INR', 'Indian Rupee'],
  ['KRW', 'South Korean Won'],
  ['BRL', 'Brazilian Real'],
  ['MXN', 'Mexican Peso'],
  ['SEK', 'Swedish Krona'],
  ['NOK', 'Norwegian Krone'],
  ['DKK', 'Danish Krone'],
  ['PLN', 'Polish Zloty'],
  ['CZK', 'Czech Koruna'],
  ['AED', 'UAE Dirham'],
  ['ILS', 'Israeli New Shekel'],
  ['ZAR', 'South African Rand'],
] as const
